### ISSUE TITLE
Error: Cannot read property 'Diagram' of undefined

### ISSUE THREAD

**Issue by Abhijit-Revamp** [jodinathan/gojs_dart#1]
Hi,

I just created a new future project (with web).
In the PUBSPEC  added
`gojs: ^1.0.0 `

In the main.dart
===============
```
import 'package:gojs/gojs.dart';
import 'dart:html' as html;

// some simple html with a div like <div id="diagram"></div>

void main() {
  var diagram = html.document.getElementById('diagram');
  
  var myDiagram = GoJSDiagram(diagram)
    ..model = GoJSModel.fromJson('''
        [
          { "key": "Alpha" },
          { "key": "Beta" },
          { "key": "Gamma" }
        ]
    ''');
}
```

In index.html I have
===============
```
<div id="diagram">
    
</div>

```

### In the debug console, getting following

` TypeError: Cannot read property 'Diagram' of undefined
    at main$ (http://localhost:58700/packages/web_table/main.dart.lib.js:13:46)
    at main (http://localhost:58700/web_entrypoint.dart.lib.js:31:27)
    at main.next (<anonymous>)
    at http://localhost:58700/dart_sdk.js:37584:33
    at _RootZone.runUnary (http://localhost:58700/dart_sdk.js:37438:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:58700/dart_sdk.js:32422:29)
    at handleValueCallback (http://localhost:58700/dart_sdk.js:32969:49)
    at Function._propagateToListeners (http://localhost:58700/dart_sdk.js:33007:17)
    at async._AsyncCallbackEntry.new.callback (http://localhost:58700/dart_sdk.js:32733:27)
    at Object._microtaskLoop (http://localhost:58700/dart_sdk.js:37699:13)
    at _startMicrotaskLoop (http://localhost:58700/dart_sdk.js:37705:13)
    at http://localhost:58700/dart_sdk.js:33224:9Application finished.`

**Comment by jodinathan** [comment]
did you include the js file in the html?

**Comment by Abhijit-Revamp** [comment]
Thanks. I think this just needs a bit of documentation update.

Nice work overall.

**Comment by AmbujaAK** [comment]
> did you include the js file in the html?

I am getting the same issue, how can i include js file to resolve this issue ?

**Comment by jodinathan** [comment]
> > did you include the js file in the html?
> 
> I am getting the same issue, how can i include js file to resolve this issue ?

https://gojs.net/latest/download.html

example:
```
<script src="https://unpkg.com/gojs/release/go.js"></script>
```

you can do it in a specific HTML or in your index.html for global use

**Comment by techttiru** [comment]
@AmbujaAK @Abhijit-Revamp @jodinathan - Hi, I am also facing the similar problem. can some one please explain how to solve this? i did add this js file in index.html but still getting the issue. i have explained the steps that i followed in the below issue ticket.
[https://github.com/jodinathan/gojs_dart/issues/2](https://github.com/jodinathan/gojs_dart/issues/2)

Appreciate your quick response!.
